# Generated by Django 5.1.3 on 2024-12-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(max_length=255),
        ),
    ]
