# Generated by Django 3.1.3 on 2020-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201003_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_pic',
            field=models.ImageField(blank=True, null=True, upload_to='chat_pics/'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unseen', 'unseen'), ('present', 'present'), ('seen', 'seen')], default='unread', max_length=10),
        ),
    ]
