# Generated by Django 3.1.3 on 2020-12-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201129_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('unseen', 'unseen'), ('present', 'present'), ('seen', 'seen')], default='unseen', max_length=10),
        ),
    ]
